### ISSUE TITLE
[port download failure] sentry-native

### ISSUE THREAD

**Issue by danieljurek-extern** [danieljurek/vcpkg-cache-builder#58]
Missing hashes identified for port sentry-native

Build: https://github.com/danieljurek/vcpkg-cache-builder/actions/runs/7380927050

> [!NOTE]
> This list is updated by automation and may change as assets cycle out

* 0fa548b70e3fbb87614521d797a577ffa185991f0942cf20dd965f8c068414512a63f5d715672ecf243aa31d18fdcda6ce355ad8614ede7b988d0a103cda7244

To fix: 
* If the SHA is not valid or the port has build problems
    * Add to ignore-ports.txt or ignore-hashes.txt 
* Ensure that the port downlaods successful which might include...
    * Ensuring that a required triplet is present (easiest)
    * Building the port to download the asset (needs build infrastructure)
    * Ensure features are properly configured

**Comment by danieljurek-extern** [comment]
Missing hashes identified for port sentry-native

Build: https://github.com/danieljurek/vcpkg-cache-builder/actions/runs/7380927050

> [!NOTE]
> This list is updated by automation and may change as assets cycle out

* 0fa548b70e3fbb87614521d797a577ffa185991f0942cf20dd965f8c068414512a63f5d715672ecf243aa31d18fdcda6ce355ad8614ede7b988d0a103cda7244

To fix: 
* If the SHA is not valid or the port has build problems
    * Add to ignore-ports.txt or ignore-hashes.txt 
* Ensure that the port downlaods successful which might include...
    * Ensuring that a required triplet is present (easiest)
    * Building the port to download the asset (needs build infrastructure)
    * Ensure features are properly configured

**Comment by danieljurek-extern** [comment]
Missing hashes identified for port sentry-native

Build: https://github.com/danieljurek/vcpkg-cache-builder/actions/runs/7380927050

> [!NOTE]
> This list is updated by automation and may change as assets cycle out

* 0fa548b70e3fbb87614521d797a577ffa185991f0942cf20dd965f8c068414512a63f5d715672ecf243aa31d18fdcda6ce355ad8614ede7b988d0a103cda7244

To fix: 
* If the SHA is not valid or the port has build problems
    * Add to ignore-ports.txt or ignore-hashes.txt 
* Ensure that the port downlaods successful which might include...
    * Ensuring that a required triplet is present (easiest)
    * Building the port to download the asset (needs build infrastructure)
    * Ensure features are properly configured

**Comment by danieljurek** [comment]
Hash(es) not listed in the current version of vcpkg and not actively requested. Skipping.
