### ISSUE TITLE
[port download failure] shader-slang

### ISSUE THREAD

**Issue by danieljurek-extern** [danieljurek/vcpkg-cache-builder#59]
Missing hashes identified for port shader-slang

Build: https://github.com/danieljurek/vcpkg-cache-builder/actions/runs/7380927050

> [!NOTE]
> This list is updated by automation and may change as assets cycle out

* 627d77d83eef56e25815c30d0e99ae472c9189c760d1a620daebf49407c97e5e4da4b7880781c7788e85c5ccfba3a9e938e50ede2be0e93c0635050b11ad22a0
* e898c20c60b4f3e8bbb262fef4cad88fba35b66dafb4784eec8b1603d8ee0293a71faeac1f84a9df96f33e206503ed717f7a068370e40a49bac90c009bbe4336

To fix: 
* If the SHA is not valid or the port has build problems
    * Add to ignore-ports.txt or ignore-hashes.txt 
* Ensure that the port downlaods successful which might include...
    * Ensuring that a required triplet is present (easiest)
    * Building the port to download the asset (needs build infrastructure)
    * Ensure features are properly configured

**Comment by danieljurek-extern** [comment]
Missing hashes identified for port shader-slang

Build: https://github.com/danieljurek/vcpkg-cache-builder/actions/runs/7380927050

> [!NOTE]
> This list is updated by automation and may change as assets cycle out

* 627d77d83eef56e25815c30d0e99ae472c9189c760d1a620daebf49407c97e5e4da4b7880781c7788e85c5ccfba3a9e938e50ede2be0e93c0635050b11ad22a0
* e898c20c60b4f3e8bbb262fef4cad88fba35b66dafb4784eec8b1603d8ee0293a71faeac1f84a9df96f33e206503ed717f7a068370e40a49bac90c009bbe4336

To fix: 
* If the SHA is not valid or the port has build problems
    * Add to ignore-ports.txt or ignore-hashes.txt 
* Ensure that the port downlaods successful which might include...
    * Ensuring that a required triplet is present (easiest)
    * Building the port to download the asset (needs build infrastructure)
    * Ensure features are properly configured

**Comment by danieljurek** [comment]
Hash(es) not listed in the current version of vcpkg and not actively requested. Skipping.
