### ISSUE TITLE
[port download failure] matio

### ISSUE THREAD

**Issue by danieljurek-extern** [danieljurek/vcpkg-cache-builder#60]
Missing hashes identified for port matio

Build: https://github.com/danieljurek/vcpkg-cache-builder/actions/runs/7380927050

> [!NOTE]
> This list is updated by automation and may change as assets cycle out

* b9a1abe88565bb01db9aa826248b63927e8576d4e9b72665dee53cc29e0baf6c7af232f298fb6a22b3b96d820cb692ff29f98e2d0d751edc22a5f1ee884fc2df

To fix: 
* If the SHA is not valid or the port has build problems
    * Add to ignore-ports.txt or ignore-hashes.txt 
* Ensure that the port downlaods successful which might include...
    * Ensuring that a required triplet is present (easiest)
    * Building the port to download the asset (needs build infrastructure)
    * Ensure features are properly configured

**Comment by danieljurek** [comment]
Hash(es) not listed in the current version of vcpkg and not actively requested. Skipping.
