### ISSUE TITLE
[port download failure] qtbase

### ISSUE THREAD

**Issue by danieljurek-extern** [danieljurek/vcpkg-cache-builder#61]
Missing hashes identified for port qtbase

Build: https://github.com/danieljurek/vcpkg-cache-builder/actions/runs/7380927050

> [!NOTE]
> This list is updated by automation and may change as assets cycle out

* 42a5df24b57afc5d60d33d6e6dc4021b9c1dbaba2fb7cab251ab636df8457619ee55177d6fe3dd93db335f271a3b40a86a9f7a3c76e34373ed7bce449a9b0652
* 6563d23d48c828a7895279c42befa2275b02301fa16906494ea84a9c80076ea5c7f1be773a52f483dab5d8304feedfd9c5df4ac83cd77284aacae0287760555a
* 3c62b0b1425815fbbeb1d46cc3599edbf5c3b07f1f28840801d34620c0fe81740ad4b70743b72e8a52bdabcb14d77378f1c3fabae4eae2d29e017c8f40923205
* d6eb6ab52281e8b78de2a28aeaa1c0f9107634b5ada9700a4bad4f6fa66e2983dad6566b99d030d0980dd9817395fa033ebee7b79960fa527882b9239e908ff7
* 2b34f596c04eb7d24c83bd09c5a1a10923c0a0e7e94af5443b58c5b41285067da46ff06686877431fa7d385e07e019a1617f15a0bb6a423849d7288bafb41c2e
* a2f8c1d7075fdaf57d7d4fc5f087449ef1a78ea6b6ab4ae7801decdb2436b7f95aefadaf365ab7c2ad0ceaf1f066c3c0ea189f3e3a18d41b89e391e6e5f33940
* 309800ad6afc1959d83d7dba97af41954b813486740f99747df6d997a3420c3a9fcc97e52ae67a390b34885ca9bc683cdecea55dd2ab4b530e7594654fa13454
* 99dfd8a2e13f7862a21f9bccde4aa719bca1136addcc3e144fed0632a7d2341b27a44432c36d96ea221e6b5a9b6135241c1f2deeec5be3cbd40e5257ce3f8b77
* e9cf63ccc71d4dc61b04a0f8a1a466e9ede09aa689c53c1ccc9db5233e324894bfd198c9204d8d93509c770a7a6612c8eb9981e0b3ee7428f8bf2dcbdc255109
* 15593b8bc37c7e8f5082e0c201e6a99a7646feed52b44dffb46d41d555e7cb060185229c3e271631ec3730947df25af0294561304a8352022e5f5688167ee78d
* 27f3f48d3e8e32672194ce2377dc02974d01d5714071104359bb8003999a9b9184170da0ee618449493724036305a9ed47cfdf12fd4a63dfd48671114b05d11b
* d019c8dfc077a725704923234a9ef86d9ce68fdfb1187d18ff3bd9c6a5cc53ac502a67bbf27b70fc20807e99e9eb7d5da094a19bd8cedc1a2e51cc679a7e478f
* e68d945abfd6f099abeb29d97beff90dd4856c9ad05491e440536edfbf299d1aba32eefc519a87d7e61f9ffcb4cd142ecb4e9d3c2aa10f93b5033de99e8ad0d1
* 22727b04340adffdb0f260cce46b57181c721aab29a1676c42ee64ef4df330556804286357143f858853e10e94230158d7d245d374925c4bab1ab385a4698252
* 5954da0478459f217979f6feba067ab4c42333995a203c3245289fcd9b966d18d0824099ff673d9e8a954562ff26595076be727f13194b3318060b7dbcab6ce9
* 7339fc08173793949f28b117c610e42bd25094d186b93db0a244c429e5232d9f5918247c654ee6c6f66802943eeadd1a545261a98b83db71e20b7867f27d94a7
* 8f5271ee72499a2965f040ba4f2f7604f23d3c37b828612d7482b6b799b12875da5b916899e80b572a0d7217ce4349389e1e72701438fb9855bc7dbbf1ef6dbd
* fc65c9a0685973bc39d2d54a40d537d9be99c442922c8f60db2c02d7c5ed2e33e4aeaa4c4c76267c6660aa66b6bdd3544d1c371925de74657512a5961b558965
* 26659891a2bb4773ccd9cff8cf8a4e69d3b3649842a1dadb5efb62bb5e7411fb0c9d6d41321d1c850668942999ec55fdc5b54b8fde82fd0571a30d90653bacbb
* d565095945ea18d8524c993f428bc279e755ee5860e4888e7bbd553187aaed0b979fe864f518a439fcdbc663a9176168eebf338d76656876c945e8a21e3ba5f2
* ccb4c04048d4c18625b890b6a84a4ccf12108df88c0af0dff2dfa64b504116802fd6061226f991a212016210ab468f520d44bf4299d3ae79e7fe873e4d10c120
* 5bf8c8b892c5398bf78662be3f44fbeb2f7dc96bf4ee88739f778c6427e5c8fd9f3e80356b9bd0ebea8f8adb733de44de51e8aaa6009b7cc52f0d0b5bfd3658b
* 87659269eebeb36558337f1e7a954d93f9a0d4b7783611fa47a562c1f7e60b4f228e58650f69aacc72c656f322d3a5763a662206228667aeb32b16242b912bd2
* f660edbfaa9aefebdb602bb44b2e62b8a5d8dceba4b8c3d73d0f9daf6c29ff5f8953c134dc5af79dfd90b888f97d99e44f91a8e0aee3a51b278747eee2d1c381
* 6e71563444b1d3102ba6ad4ad04541b7ea3f7ee8737ebab76f7c8f7df5ac8e57afa0612bf634b97da5b7a424f7b2dcf28d57f5e67b91266a5138cbd41de8a0f3
* e4e492229d961bc34630aaff030b46385708312de174c9c47f85a6010f1fcb74e198333920fd5c02153a8bbae770c83d8cd1777177d9c9d7a1d555b6619be8f2
* ccfdd1aaed76dfb06692e212405d9b2804aa3da924c903febf5ee3fde057f4543f76284a543c808f600d61b5eadfbfe2437932f5ff4a7d19941c9ab3eae2d8a0
* ef1307247e8355bdc8fd38255d8d75d821bbcdd4098e11e04ff1d63dc11656c7a52a99d4398fd437efc6df782130a2d10820c697385bc8901bb2e182340e91d3
* d7aa9a9c06c3c2c090a7ea570a9f01914ff62775ae9b6c4e4f6296e0f891d5b45fd0bedd04cebf02e314f73e8ccb8997bffe05ef04c19421f66638a4781a4b7d
* 90ec1ebba16247781e294d482257314f681f668d0abea84862d4f64bc09bafdaea5081098a5df716f22c1d0098862aa3ea3d4eba167470e0c35c4181dbe8366b
* 8fc91ed80a7a58b2126f746a1148f64d34812574180d9b8609629e93903ce6d026f279aac87e0acd90f995d57ba12290fe57294ca15482c035337566ffe51fc6
* bffa1aeaefc1b3b5e8d0f958a689b9debd37134ed705f029c2edbd0c483181a474648c251e4921fc8a3d32ce6c1632e82ddba51c55cfb49843cf022870f053f7
* 30469cf50d84e4547f0cf76b78b921fab550958d812cfcb894cf03ffcd0b1cbd3c1dc9314835ca6b5a182cbabdd236cb315bcc288d999f23c10d7ab0763a6366
* c679be915ed3831778d527d29a8a7277cdfe3912dbfd3d813750006c41c9433786122306db658bb5c1c22e22da9cdc339794b53c4f6c36d4603e98ddff60f0ef
* f76a64a36388e8fc7376d045dde6a54cfefb13c2b72378d9f7d35cc7c91c8a02ed8973918b335e67fc326967ae64a07fe685c521f5e0b30494d5e0a931b27b74
* 5c0f8f9b73bc3531727af9cb0175c1cc6487f81cfdc8574b53e5ce88375d767cd8b4d912a39545eab0219465ff633d913fb769fc44fc9715702f90e168117d81
* 58bc24427f7f33772bebfd5a67c091315b4c913a3c8d6c48a151046543e2756c4c2b0fa03e64bc6b1c760b28849b19676e86b24c4242353fd0aff5b8fa6015d5
* 06e501042d4fb78f4ade4093fc05940373156cc2fedc11f0a3b2191cc975fd92e660921c0c88ebc124cf243457f0dfedf7a1f32d30cd24e7fc74397191edd79d
* aba0669499ccc4989d50d3bd00b591317a8f09d234767f6ae10c360989a002a7426dc867c19843701e7a7f14b526c18be50274d5a30638e74a80e4257c6490f8
* 29fc5e2401ac0d184ca5931c86eba152d33433ef60e91e3c30fdce79438e13f89b9f7ea01452c528fabd24425a9396c6d6f18b8d7d085a002073f0d27ec2a56a
* e839d7a79349c33460850384933317af61c77abe90682566d8d457470619ca0571190befa91f71c8ba358f5320c11ac0090dffd29b99145134702fa571bb2432
* 7f89c05cc421a90c0006f3411a9965f27ada45de149a0ce0ca0f9d3b6d0a05ab5409e3cc66aa7cf8563b4d0796c77eb17976c56c03d65bc0724f0451eb0b810b

To fix: 
* If the SHA is not valid or the port has build problems
    * Add to ignore-ports.txt or ignore-hashes.txt 
* Ensure that the port downlaods successful which might include...
    * Ensuring that a required triplet is present (easiest)
    * Building the port to download the asset (needs build infrastructure)
    * Ensure features are properly configured

**Comment by danieljurek** [comment]
Hash(es) not listed in the current version of vcpkg and not actively requested. Skipping.
