### ISSUE TITLE
[port download failure] imgui

### ISSUE THREAD

**Issue by danieljurek-extern** [danieljurek/vcpkg-cache-builder#62]
Missing hashes identified for port imgui

Build: https://github.com/danieljurek/vcpkg-cache-builder/actions/runs/7380927050

> [!NOTE]
> This list is updated by automation and may change as assets cycle out

* ac6117f6adf9418af3a2db5392f1316be50a94c38e78cd1eadc0e0a71dfbb5536507aaf4d9d3b3468b5a30ebf143b806e2774f274e2098e1217ed93080fe81c7

To fix: 
* If the SHA is not valid or the port has build problems
    * Add to ignore-ports.txt or ignore-hashes.txt 
* Ensure that the port downlaods successful which might include...
    * Ensuring that a required triplet is present (easiest)
    * Building the port to download the asset (needs build infrastructure)
    * Ensure features are properly configured

**Comment by danieljurek-extern** [comment]
Missing hashes identified for port imgui

Build: https://github.com/danieljurek/vcpkg-cache-builder/actions/runs/7380927050

> [!NOTE]
> This list is updated by automation and may change as assets cycle out

* ac6117f6adf9418af3a2db5392f1316be50a94c38e78cd1eadc0e0a71dfbb5536507aaf4d9d3b3468b5a30ebf143b806e2774f274e2098e1217ed93080fe81c7

To fix: 
* If the SHA is not valid or the port has build problems
    * Add to ignore-ports.txt or ignore-hashes.txt 
* Ensure that the port downlaods successful which might include...
    * Ensuring that a required triplet is present (easiest)
    * Building the port to download the asset (needs build infrastructure)
    * Ensure features are properly configured

**Comment by danieljurek-extern** [comment]
Missing hashes identified for port imgui

Build: https://github.com/danieljurek/vcpkg-cache-builder/actions/runs/7380927050

> [!NOTE]
> This list is updated by automation and may change as assets cycle out

* ac6117f6adf9418af3a2db5392f1316be50a94c38e78cd1eadc0e0a71dfbb5536507aaf4d9d3b3468b5a30ebf143b806e2774f274e2098e1217ed93080fe81c7

To fix: 
* If the SHA is not valid or the port has build problems
    * Add to ignore-ports.txt or ignore-hashes.txt 
* Ensure that the port downlaods successful which might include...
    * Ensuring that a required triplet is present (easiest)
    * Building the port to download the asset (needs build infrastructure)
    * Ensure features are properly configured

**Comment by danieljurek** [comment]
Hash(es) not listed in the current version of vcpkg and not actively requested. Skipping.
