### ISSUE TITLE
[port download failure] live555

### ISSUE THREAD

**Issue by danieljurek-extern** [danieljurek/vcpkg-cache-builder#63]
Missing hashes identified for port live555

Build: https://github.com/danieljurek/vcpkg-cache-builder/actions/runs/7380927050

> [!NOTE]
> This list is updated by automation and may change as assets cycle out

* d0708a087d9252b2f13d7b2e14c47e24e895ac329d5dd640a00756e92c846c57573198f6cc79e88272567babf5b0bb8cb268e750685efe8b9693fd9aec384e70

To fix: 
* If the SHA is not valid or the port has build problems
    * Add to ignore-ports.txt or ignore-hashes.txt 
* Ensure that the port downlaods successful which might include...
    * Ensuring that a required triplet is present (easiest)
    * Building the port to download the asset (needs build infrastructure)
    * Ensure features are properly configured

**Comment by danieljurek-extern** [comment]
Missing hashes identified for port live555

Build: https://github.com/danieljurek/vcpkg-cache-builder/actions/runs/7380927050

> [!NOTE]
> This list is updated by automation and may change as assets cycle out

* d0708a087d9252b2f13d7b2e14c47e24e895ac329d5dd640a00756e92c846c57573198f6cc79e88272567babf5b0bb8cb268e750685efe8b9693fd9aec384e70

To fix: 
* If the SHA is not valid or the port has build problems
    * Add to ignore-ports.txt or ignore-hashes.txt 
* Ensure that the port downlaods successful which might include...
    * Ensuring that a required triplet is present (easiest)
    * Building the port to download the asset (needs build infrastructure)
    * Ensure features are properly configured

**Comment by danieljurek** [comment]
Hash(es) not listed in the current version of vcpkg and not actively requested. Skipping.
